### PR TITLE
Rtc 127454 syslog t intermittent

### PR DESCRIPTION
**Pull request by jkeenan**
For [RTC 127454](https://rt.cpan.org/Ticket/Display.html?id=127454)

If this pull request is acceptable, I would request that you provide a new CPAN release at your earliest convenience.  That way we can see whether the failures which Perl 5 smoke testers are reporting are cleared up.

Thank you very much.
Jim Keenan

### CODE REVIEW

**Comment by jkeenan** [comment]
Maddingue, could you please evaluate this p.r. which has been pending for five months now?  We would really like to get spurious smoke-test failures cleared up.

Thank you very much.

**Comment by jkeenan** [comment]
Maddingue, could you please evaluate this p.r. which has been pending for nine months now? We would really like to get spurious smoke-test failures cleared up.

Thank you very much.

**Comment by jkeenan** [comment]
Thank you for investigating this.  My preliminary investigation suggests that the Sys-Syslog tests are no longer failing in my smoke-tests of Perl 5 on OpenBSD.

However, so that we can be certain of the results, can you do a new CPAN release of Sys-Syslog (with incremented version number) at your earliest opportunity?  We will then synch Perl 5 blead with CPAN.  (Blead is the branch that gets smoke-tested most vigorously.)

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Do you know when a new CPAN release for Sys-Syslog will be forthcoming?

Thank you very much.
Jim Keenan

**Comment by maddingue** [comment]
Apologies for being so long to merge your commit, and after that to make the release. While working on the code, I was trying to address [CPAN RT #130154](https://rt.cpan.org/Public/Bug/Display.html?id=130154) as well.

I've just uploaded release 0.36 on the CPAN.

**Comment by jkeenan** [comment]
On 10/22/19 12:45 AM, Sébastien Aperghis-Tramoni wrote:
> Apologies for being so long to merge your commit, and after that to make 
> the release. While working on the code, I was trying to address CPAN RT 
> #130154 <https://rt.cpan.org/Public/Bug/Display.html?id=130154> as well.
> 
> I've just uploaded release 0.36 on the CPAN.
> 

Thanks for your intervention.  BINGOS synchronized blead with version 
0.36, so it's now in blead.  I've confirmed that we no longer get test 
failures on NetBSD, but I still need to test on OpenBSD.  That may take 
several more days, as I do not have the best internet connectivity right 
now.  Please ping me if I do not update this by a week from now.

Thank you very much.
Jim Keenan

**Pull request merged**
